before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: KCdhb9ywZtgyV8ynHjAYTSyv9d71OK+POc35NGIXuGzJPkd2zqwdCwdjErTJX7tTZ66gumTvHwsXIDUd12BikKJgEqSdoPzdwwQjp8Pzexi1hpA2+efjjvbAGgu/pPSPvTkjEsI9AzZS8ROm2iYARFX+g75bj4f+Dkd4pxqztVtq83yiHFZigDmVvWziKzaLgql7aUevT6uNNBnZKN/QAiPFQ9LF5uQ7n6QvngpWSrJo0nmINsuQjrJWNTLvR+l/bcajau7v4gz3rQOGhtzHGYW4Dt13T888rABcoP7AVRN18eOPih8l2R+H1qymIbU892w+9ENErVZJZdhNklIEl1jzptEDraZ0WfuUqw0yyC4ZJVvxn59UD+DWDDrf00ZI69QX7hVrTsYRvoEj7CPFYOPdeZ/l3zDpa9oar7uaeASdrZaDISgfOoEn1eqUXN2M4WwA3jgAnqsTgjgHgywqUboh2y0o/zghO3aOdSvSRUmbTmJ9QB8VhUU/pslW5kRWgBaDAEOyC7R/Nlhk7G8XPjULQP7DxXLCuNhP76BkdJqWfnAgisFgDP7UuVFBHtjPHVZm/ItuXH/CTKIXbU9muRBBETYsD3fAovGJIggPS80TuTb5mSoQZA0zLha0AT5VSJRZsemBZNL6bDN756150SSRDkX0BAzaItsM+toiF2o= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
